# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIpyMol.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from pymol.Qt import QtCore, QtGui, QtWidgets
from Bio.PDB import PDBParser
from pymol import cmd
from PySupercharge import AvNAPSA_class

def __init_plugin__(app=None):
    from pymol.plugins import addmenuitemqt
    addmenuitemqt('Show AvNAPSA', run_plugin_gui)

pyqt = None

def run_plugin_gui():
    global pyqt
    pyqt = QtWidgets.QWidget()
    ui = Ui_pyqt()
    ui.setupUi(pyqt)
    pyqt.show()


class Ui_pyqt(object):
    def setupUi(self, pyqt):
        pyqt.setObjectName("pyqt")
        pyqt.resize(252, 293)
        self.verticalLayout = QtWidgets.QVBoxLayout(pyqt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(pyqt)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(pyqt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setMinimumSize(QtCore.QSize(15, 0))
        self.spinBox.setMaximum(9999)
        self.spinBox.setProperty("value", 80)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonImportPDB = QtWidgets.QPushButton(pyqt)
        self.buttonImportPDB.setObjectName("buttonImportPDB")
        self.verticalLayout.addWidget(self.buttonImportPDB)
        self.buttonAvNAPSA = QtWidgets.QPushButton(pyqt)
        self.buttonAvNAPSA.setObjectName("buttonAvNAPSA")
        self.verticalLayout.addWidget(self.buttonAvNAPSA)
        self.buttonImportConsurf = QtWidgets.QPushButton(pyqt)
        self.buttonImportConsurf.setObjectName("buttonImportConsurf")
        self.verticalLayout.addWidget(self.buttonImportConsurf)
        self.buttonShowConsurf = QtWidgets.QPushButton(pyqt)
        self.buttonShowConsurf.setObjectName("buttonShowConsurf")
        self.verticalLayout.addWidget(self.buttonShowConsurf)
        spacerItem2 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(pyqt)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(pyqt)
        QtCore.QMetaObject.connectSlotsByName(pyqt)

        #============== Default Parameters ==================

        self.protein    = None
        self.atoms      = None
        self.buttonAvNAPSA.setVisible(False)
        self.buttonShowConsurf.setVisible(False)

        #============== Connecting to Backend ==================

        self.buttonImportPDB.clicked.connect(lambda: self.importPDB())
        self.buttonAvNAPSA.clicked.connect(lambda: self.showAvNAPSA())


    def importPDB(self):
        import ntpath

        def path_leaf(path):
            head, tail = ntpath.split(path)
            return tail or ntpath.basename(head)

        try:
            filename,_filter = QtWidgets.QFileDialog.getOpenFileName(None, 'Select PDB File', '.pdb')

            cmd.load(filename)
            p = PDBParser()
            proteinName     = path_leaf(filename)
            self.protein    = p.get_structure(proteinName,filename)
            self.atoms      = AvNAPSA_class.readPDB(filename=filename)

        except Exception as e:
            print('Error: '+str(e))

        if self.protein != None:
            self.buttonAvNAPSA.setVisible(True)


    def showAvNAPSA(self):
        assert self.protein != None and self.atoms != None

        thres = int(self.spinBox.value())
        AvNAPSA, residues = AvNAPSA_class.getAvNAPSA(self.protein, self.atoms,thres=thres)

        # lines = cmd.get_pdbstr().splitlines()
        # resiNum = set([int(line[22:26].strip()) for line in lines if line[:4] == 'ATOM' ])
        residues = 'resi ' + '+'.join([str(res.resNum) for res in residues])
        cmd.select('AvNAPSA', residues)
        cmd.color('red', 'AvNAPSA')


    def retranslateUi(self, pyqt):
        _translate = QtCore.QCoreApplication.translate
        pyqt.setWindowTitle(_translate("pyqt", "Show AvNAPSA"))
        self.buttonImportPDB.setText(_translate("pyqt", "import PDB"))
        self.buttonAvNAPSA.setText(_translate("pyqt", "Show AvNAPSA"))
        self.buttonImportConsurf.setText(_translate("pyqt", "Import ConSurf"))
        self.buttonShowConsurf.setText(_translate("pyqt", "Show Consurf"))
        self.label.setText(_translate("pyqt", "by Hieu @ AhnLab"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     pyqt = QtWidgets.QWidget()
#     ui = Ui_pyqt()
#     ui.setupUi(pyqt)
#     pyqt.show()
#     sys.exit(app.exec_())
